### PR TITLE
Iso image

### PR DESCRIPTION
**Pull request by c-po**
This adds a new target "vyos-iso-image" which builds a bootable CD image for x86 systems.

The main goal is to have a VyOS yocto build close to the current available x86 ISO.

### CODE REVIEW

**Comment by wtolkien** [comment]
Thanks again for your contributions - I had been working on switching meta-vyos to systemd to better stay in sync with upstream VyOS. Not surprisingly this broke a few things and it took a while to stabilize it - hence the big patchset just now.

I also switched to Yocto 2.5 ('Sumo') even though it's not final yet. Given that meta-vyos is still in alpha stage, it seems to make sense to catch any Sumo-related issue at this stage already and then possibly lock things down to 'Sumo' when it's released. 

As for having an X86 ISO image, I can see the usefulness because it eliminates the requirement for embedded hardware for people who want to contribute here. 

However, there are some possible conflicts and I'm wondering what your thoughts are:
- kernel config: embedded hardware can use a very narrow tailored config whereas X86 needs pretty much every driver enabled. 
- image management and upgrades: upstream VyOS mechanisms are not well suited for embedded systems with limited storage. I was planning to use swupdate for upgrades, using a dual image partitioning scheme with an additional persistent partition for config, etc.
- image size and feature set: some upstream VyOS features can be (and should be) removed in embedded systems: RAID, SCSI, the ability to run as a live-system and install on a HDD, etc.

**Review by wtolkien — APPROVED** [review]

**Review by wtolkien — CHANGES_REQUESTED** [review]
Could we make things dependent on the target being embedded/non-embedded? For example, maybe using

RDEPENDS_${PN}_append_x86 = " lsscsi"
RDEPENDS_${PN}_append_x86-64 = " lsscsi"

or by introducing a 'vyos-embedded' distro feature or image feature and using that throughout?

**Comment by c-po** [comment]
Unfortunately `lsscsi` is deeply embedded in the VyOS scripts itself. Currently we are re-writing alot of the VyOS code inherited from Vyatta core.

I think until this is complete we have to pull in additional features like this. If there is a `vyos-embedded` distro feature we possible could remove installed files/scripts not present in embedded devices from the generated rootfs in a post build step? Would this sound reasonable?

**Comment by c-po** [comment]
Regarding Kernel configuguration, I have yet no embedded device but my Ubiquity ERPro is expected to be delivered by tomorrow. But I know from different projects that embedded Kernels are hand crafted to the target (let me see).

The ERPro8 is supposed to be my VyOS (embedded w/meta-vyos) target hardware. By getting this up and running.

Personally I have yet no to none experience w/ swupdate but I think it's the right way to go. I only have to figure out how it works.

**Comment by wtolkien** [comment]
I guess one of the core issues is what direction this project (meta-vyos) should take. Initially I planned it for embedded devices, but of course the thought crossed my mind that it could also be used for X86. 

Heck, it would even be possible for Yocto to replace Debian in upstream VyOS one day. After all, that's the very definition of Yocto according to their web site: "The Yocto Project.  It's not an embedded Linux Distribution, It creates a custom one for you."

However, that would be pretty presumptuous and I'm not even sure if the benefits would outweigh the effort that would be required to make that happen. 

My other goal is to make meta-vyos stable and usable. And realistically, that means limiting the amount of target platforms unless there is a huge influx of contributors. And even then, I feel that for example  OpenWRT/Lede went too far in supporting many different platforms which impacted stability. But maybe I'm being unfair to them and things have improved now - I'm not up-to-date here...

Regarding the kernel, I would suggest to try and stick to 4.14 for all platforms for now, after all that's what VyOS 1.2 uses. My current kernel config comes from the meta-mediatek repo ('linux-mtk') and is customized for that target hardware. 

In general, I'm not sure about how to best handle this. linux-yocto has mechanisms to accommodate various target platforms, but I find its mechanism of creating the final '.config' too opaque for my liking. Plus, the dev/compile/test cycle seems very slow. 

I think for now having a vyos-embedded distro feature is probably the right way to go. Do you think it's better to have a single post-rootfs-build step vs. putting the code into each individual package? I would imaging it requires patching as well as removing files.

**Comment by wtolkien** [comment]
Just noticed that Yocto 2.5 "Sumo" was released a few days ago - updated Readme. Seems to work.

**Comment by c-po** [comment]
Kernel 4.14 I totally agree on. This is the latest from upstream VyOS w/ minor patches. If we should go and use the VyOS Git repo directly from SRC_URI or point to the Kernel TARball and add custom patches this is a personal choice. I'm using both at work. Of course I would keep the Kernel configuration per target machine in a machine specific subdirectory, like linux-yocto does.

Regarding the "embedded" DISTRO_FEATURE ... maybe we should reverse it to have everything "embedded" and add a DISTRO_FEATURE_scsi and so on. By this we could package individual modules into smaller packages (like util-linux is doing). By this we would get vyos-cfg-system and vyos-cfg-system-scsi (which holds additional SCSI related files. I think this is the best approach and actually that is what Yocto is good at.

This means that a "base image" for an embedded target only ships minimal packages and if you build e.g. for any x86 machine we could append the DISTRO_FEATURE scsi in the machine configuration.

**Comment by wtolkien** [comment]
That does indeed make sense and you are right, that would very much be the Yocto way of doing things. However, I worry that by making things so granular, it creates many different combinations of config options. I.e. just having 3 features such as 'scsi', 'raid', 'image-management' creates 8 different combinations that would have to be tested. I know that I won't have the cycles to do that. Will you? Otherwise, the reality will probably be that people either turn everything on for X86, or everything off for embedded because any combination in between might be unstable. That means we would effectively be back to 'embedded' or 'non-embedded'.

**Comment by c-po** [comment]
I certainly have no cycle time, too. So then we use embedded/non-embedded and we could still create a non-embedded additional package with those files in thus the permutation is reduced to 2 (embedded and non-embedded) I think the lsscsi is a good starting point for this b/c I also don't see any SCSI stuff in EdgeOS.

**Comment by wtolkien** [comment]
Sounds good! Thanks!

**Comment by c-po** [comment]
Rebased everything to our `*/master` branch. Added new DISTRO features `vyos-embedded` and `vyos-non-embedded`. For the beginning raid and scsi is par of `vyos-non-embedded`.

Comparing two builds I see for a **QEMUX86** build
```bash
# unsquashfs -l tmp-glibc/deploy/images/qemux86/vyos-image-qemux86.squashfs | grep templates | grep scsi
squashfs-root/opt/vyatta/share/vyatta-op/templates/show/hardware/scsi
squashfs-root/opt/vyatta/share/vyatta-op/templates/show/hardware/scsi/detail
squashfs-root/opt/vyatta/share/vyatta-op/templates/show/hardware/scsi/detail/node.def
squashfs-root/opt/vyatta/share/vyatta-op/templates/show/hardware/scsi/node.def
```
**MIPS** (Edgerouter Pro)
```bash
# unsquashfs -l build-erpro/tmp-glibc/deploy/images/edgerouter/vyos-image-edgerouter.squashfs | grep templates | grep scsi
#
```

**Comment by wtolkien** [comment]
I like it, thanks!

**Pull request merged**
